version: '3.8'

services:
  vault:
    image: vault:1.12.0
    container_name: vault
    ports:
      - "8200:8200"
      - "8201:8201"
    environment:
      - VAULT_ADDR=https://0.0.0.0:8200
      - VAULT_API_ADDR=https://vault.eto.local:8200
      - VAULT_CLUSTER_ADDR=https://vault.eto.local:8201
    volumes:
      - ./config:/vault/config
      - vault-data:/vault/data
      - vault-logs:/vault/logs
      - vault-tls:/vault/tls
    cap_add:
      - IPC_LOCK
    command: server
    healthcheck:
      test: ["CMD", "vault", "status"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - vault-net
    restart: unless-stopped

volumes:
  vault-data:
  vault-logs:
  vault-tls:

networks:
  vault-net:
    driver: bridge
