apiVersion: v1
kind: Service
metadata:
  name: odoo
  namespace: etogroup
  labels:
    env: prod
spec:
  selector:
    app: odoo
  ports:
  - port: 8069
    targetPort: 8069
  type: ClusterIP
