---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"
  tags: ['system']

- name: Install required packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - git
    state: present
  when: ansible_os_family == "Debian"
  tags: ['system']

- name: Create application directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  with_items:
    - "{{ base_path }}"
    - "{{ data_path }}"
    - "{{ odoo_path }}"
    - "{{ pgadmin_path }}"
  tags: ['setup']

- name: Configure timezone
  timezone:
    name: Europe/Paris
  tags: ['system']

- name: Configure hostname
  hostname:
    name: "{{ inventory_hostname }}"
  tags: ['system']
