groups:
  - name: recording_rules
    rules:
      # Application Metrics
      - record: application:request_duration_seconds:avg_rate5m
        expr: |
          rate(http_request_duration_seconds_sum{job="eto-webapp"}[5m])
          /
          rate(http_request_duration_seconds_count{job="eto-webapp"}[5m])

      - record: application:request_errors:ratio_rate5m
        expr: |
          sum(rate(http_requests_total{job="eto-webapp",status=~"5.."}[5m]))
          /
          sum(rate(http_requests_total{job="eto-webapp"}[5m]))

      - record: application:requests:rate5m
        expr: sum(rate(http_requests_total{job="eto-webapp"}[5m])) by (path)

      # Resource Usage
      - record: node:cpu:usage_rate5m
        expr: |
          100 - (avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100)

      - record: node:memory:usage_bytes
        expr: |
          node_memory_MemTotal_bytes
          - node_memory_MemAvailable_bytes

      - record: node:disk:usage_ratio
        expr: |
          (node_filesystem_size_bytes{mountpoint="/"} 
          - node_filesystem_free_bytes{mountpoint="/"})
          / node_filesystem_size_bytes{mountpoint="/"}

      # Database Metrics
      - record: postgresql:connections:active
        expr: pg_stat_activity_count{state="active"}

      - record: postgresql:transactions:rate5m
        expr: rate(pg_stat_database_xact_commit[5m])

      - record: postgresql:deadlocks:total
        expr: pg_stat_database_deadlocks

      # Container Metrics
      - record: container:cpu:usage_rate5m
        expr: |
          sum(rate(container_cpu_usage_seconds_total{container!=""}[5m])) 
          by (container)

      - record: container:memory:usage_bytes
        expr: |
          container_memory_usage_bytes{container!=""}

      # Service Health
      - record: service:up:ratio5m
        expr: avg_over_time(up{job="eto-webapp"}[5m])

      - record: service:response_time:p95_5m
        expr: |
          histogram_quantile(0.95, 
            sum(rate(http_request_duration_seconds_bucket{job="eto-webapp"}[5m])) 
            by (le))

      # Network Metrics
      - record: network:received_bytes:rate5m
        expr: |
          sum(rate(container_network_receive_bytes_total{container!=""}[5m])) 
          by (container)

      - record: network:transmitted_bytes:rate5m
        expr: |
          sum(rate(container_network_transmit_bytes_total{container!=""}[5m])) 
          by (container)

      # SSL Certificate Metrics
      - record: ssl:cert_expiry:days_remaining
        expr: |
          (ssl_certificate_expiry_timestamp 
          - time()) / (24 * 3600)

      # Backup Metrics
      - record: backup:success:ratio24h
        expr: |
          count_over_time(backup_success_timestamp[24h]) 
          / 
          count_over_time(backup_total_timestamp[24h])
