apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  namespace: etogroup
  labels:
    env: prod
spec:
  selector:
    app: pgadmin
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
