version: '3'
services:
  odoo:
    image: odoo:13.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - odoo-web-data:/var/lib/odoo
      - odoo-addons:/mnt/extra-addons
    networks:
      - odoo_network

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    networks:
      - odoo_network

volumes:
  odoo-web-data:
  odoo-db-data:
  odoo-addons:

networks:
  odoo_network:
    driver: bridge
