apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vault
  namespace: etogroup
  labels:
    app: vault
spec:
  serviceName: vault
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: vault
          image: vault:1.12.0
          ports:
            - containerPort: 8200
              name: vaultport
              protocol: TCP
            - containerPort: 8201
              name: vaultcluster
              protocol: TCP
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
          env:
            - name: VAULT_LOCAL_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: vault-config
                  key: vault.hcl
            - name: VAULT_API_ADDR
              value: "https://$(POD_IP):8200"
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          volumeMounts:
            - name: vault-data
              mountPath: /vault/data
            - name: vault-tls
              mountPath: /vault/tls
            - name: vault-audit
              mountPath: /vault/audit
          readinessProbe:
            httpGet:
              path: /v1/sys/health
              port: 8200
              scheme: HTTPS
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /v1/sys/health
              port: 8200
              scheme: HTTPS
            initialDelaySeconds: 60
            periodSeconds: 10
      volumes:
        - name: vault-tls
          secret:
            secretName: vault-tls
        - name: vault-audit
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: vault-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
